name: CMake

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest]
        build_type: [Release, RelWithDebInfo]
        cpp_compiler: [g++, clang++, cl]
        build_shared_libs: [ON]
        include:
          - os: ubuntu-latest
            cpp_compiler: g++
          - os: ubuntu-latest
            cpp_compiler: clang++
          - os: windows-latest
            cpp_compiler: cl
        exclude:
          - os: ubuntu-latest
            build_type: Release

    steps:
    - uses: actions/checkout@v4
      with:
        submodules: recursive
        fetch-depth: 0

    - name: Install Required Packages
      if: matrix.os == 'ubuntu-latest'
      run: |
        sudo apt-get update
        sudo apt-get install nasm

    - name: Set reusable strings
      id: strings
      shell: bash
      run: |
        echo "build-output-dir=${{ github.workspace }}/build" >> "$GITHUB_OUTPUT"
        echo "vcpkg-manifest-dir=${{ github.workspace }}/libdave/cpp/vcpkg-alts/boringssl" >> "$GITHUB_OUTPUT"
        echo "cmake-toolchain-file=${{ github.workspace }}/libdave/cpp/vcpkg/scripts/buildsystems/vcpkg.cmake" >> "$GITHUB_OUTPUT"

    - name: Configure CMake
      run: >
        make configure
        BUILD_DIR=${{ steps.strings.outputs.build-output-dir }}
        CMAKE_CXX_COMPILER=${{ matrix.cpp_compiler }}
        CONFIG=${{ matrix.build_type }}
        VCPKG_MANIFEST_DIR=${{ steps.strings.outputs.vcpkg-manifest-dir }}
        TOOLCHAIN_FILE=${{ steps.strings.outputs.cmake-toolchain-file }}
        SHARED=${{ matrix.build_shared_libs }}
        SOURCE_DIR=${{ github.workspace }}

    - name: Build
      run: >
        make build
        CONFIG=${{ matrix.build_type }}
        BUILD_DIR=${{ steps.strings.outputs.build-output-dir }}
        SOURCE_DIR=${{ github.workspace }}

    - name: Test
      working-directory: ${{ steps.strings.outputs.build-output-dir }}
      run: ctest --build-config ${{ matrix.build_type }}

    - name: Move Build Output
      if: matrix.os == 'windows-latest'
      run: |
        mv ${{ steps.strings.outputs.build-output-dir }}/out/${{ matrix.build_type }}/* ${{ steps.strings.outputs.build-output-dir }}/out/
        rm ${{ steps.strings.outputs.build-output-dir }}/out/${{ matrix.build_type }}/

    - name: Upload Artifacts with Symbols
      if: matrix.os == 'ubuntu-latest'
      uses: actions/upload-artifact@v4
      with:
        name: libdavec-${{ matrix.os }}-${{ matrix.cpp_compiler }}-shared${{ matrix.build_shared_libs }}-symbolsON
        path: |
          ${{ steps.strings.outputs.build-output-dir }}/out/

    - name: Strip Symbols
      if: matrix.os == 'ubuntu-latest'
      run: |
        strip ${{ steps.strings.outputs.build-output-dir }}/out/libdavec.so

    - name: Upload Artifacts without Symbols
      if: matrix.os == 'ubuntu-latest'
      uses: actions/upload-artifact@v4
      with:
        name: libdavec-${{ matrix.os }}-${{ matrix.cpp_compiler }}-shared${{ matrix.build_shared_libs }}-symbolsOFF
        path: |
          ${{ steps.strings.outputs.build-output-dir }}/out/

    - name: Upload Artifacts
      if: matrix.os == 'windows-latest'
      uses: actions/upload-artifact@v4
      with:
        name: libdavec-${{ matrix.os }}-${{ matrix.cpp_compiler }}-shared${{ matrix.build_shared_libs }}-symbols${{ fromJSON('["ON", "OFF"]')[matrix.build_type == 'Release'] }}
        path: |
          ${{ steps.strings.outputs.build-output-dir }}/out/
